config/routes.rb
Rails.application.routes.draw do

  root 'users#index'
  
  resources :users
  resources :homes

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#failure'
  get '/signout', to: 'sessions#destroy'

end

app/models/home.rb
class Home
  include Mongoid::Document
end

app/models/user.rb
class User
  include Mongoid::Document
  field :provider, type: String
  field :uid, type: String
  field :name, type: String
  field :dob, type: String
  field :phone_number, type: Integer
  field :email
  field :oauth_token, type: String
  field :oauth_expires_at, type: Time

  def self.from_omniauth(auth_hash)
    where(auth_hash.slice(:provider, :uid)).first_or_initialize.tap do |user|
        user.provider = auth_hash.provider
        user.uid = auth_hash.uid
        user.name = auth_hash.info.name
        user.oauth_token = auth_hash.credentials.token
        user.oauth_expires_at = Time.at(auth_hash.credentials.expires_at)
        user.save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
    def current_user
        @current_user ||= User.where(uid: session[:current_user_id]).first
    end

    helper_method :current_user
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy]

  # GET /homes
  # GET /homes.json
  def index
    @homes = Home.all
    @user = User.new
  end

  # GET /homes/1
  # GET /homes/1.json
  def show
  end

  # GET /homes/new
  def new
    @home = Home.new
  end

  # GET /homes/1/edit
  def edit
  end

  # POST /homes
  # POST /homes.json
  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: 'Home was successfully created.' }
        format.json { render :show, status: :created, location: @home }
      else
        format.html { render :new }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homes/1
  # PATCH/PUT /homes/1.json
  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { render :show, status: :ok, location: @home }
      else
        format.html { render :edit }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1
  # DELETE /homes/1.json
  def destroy
    @home.destroy
    respond_to do |format|
      format.html { redirect_to homes_url, notice: 'Home was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def home_params
      params.fetch(:home, {})
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ActionController::Base

  def create
    user = User.from_omniauth(auth_hash)
    session[:current_user_id] = auth_hash['uid']
    # session[:current_user_hash] = auth_hash["info"]["user"]
    session[:current_user_access_token] = auth_hash['credentials']['token']
    redirect_to "http://localhost:3000/users/sign_in?guest_login=true&email=gueststu@avanti.in&password=avanti"
    # redirect_to root_url
  end

  def destroy
    session[:current_user_id] = nil
    redirect_to root_url
  end

  protected

    def auth_hash
      request.env['omniauth.auth']
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @user = User.new
  end

  def show
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.fetch(:user, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/_form.html.slim
= form_for form_object , html: {class: 'form-horizontal',role: 'form', "data-toggle" => 'validator'} do |f|
      .form-container-unit
        = f.label :name
        = f.text_field :name, autofocus: true, class: "form-control", placeholder: t("user.p-name"), "data-error" => t("user.name"), required: true
        /= errors_for @user, :name
        .help-block.with-errors
      .form-container-unit
        = f.label :email
        = f.text_field :email, autofocus: true, class: "form-control", placeholder: t("user.p-email"), "data-error" => t("user.email"), required: true
        /= errors_for @user, :email
        .help-block.with-errors
      .form-container-unit
        = f.label :phone_number
        = f.text_field :phone_number, autofocus: true, class: "form-control", placeholder: t("user.p-phone_number"), "data-error" => t("user.phone_number"), required: true
        /= errors_for @user, :phone_number
        .help-block.with-errors
      .form-container-unit#save-details
        = f.submit 'Submit',class: "btn btn-lg btn-primary btn-block"

app/views/homes/edit.html.slim
h1 Editing home

== render 'form'

= link_to 'Show', @home
'|
= link_to 'Back', homes_path

app/views/homes/index.html.slim
body
  /! Navigation
  nav.navbar.navbar-default.navbar-fixed-top.topnav role="navigation"
    .container.topnav
      /! Brand and toggle get grouped for better mobile display
      .navbar-header
        button.navbar-toggle data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button"
          span.sr-only Toggle navigation
          span.icon-bar
          span.icon-bar
          span.icon-bar
        div.navbar-brand.topnav
          - if current_user
            | Signed in as &nbsp;
            strong
              = current_user.name
            |, &nbsp;
            strong.h2
              = link_to 'Sign out', signout_path, id: 'sign_out'
          - else
            = link_to 'Sign in with Facebook', '/auth/facebook', id: 'sign_in'
        / a.navbar-brand.topnav href="/auth/facebook"  onclick="checkLoginState()" Log in with Facebook
      /! Collect the nav links, forms, and other content for toggling
      #bs-example-navbar-collapse-1.collapse.navbar-collapse
        ul.nav.navbar-nav.navbar-right
          li
            a href="#about"  About
          li
            a href="#services"  Services
          li
            a href="#contact"  Contact
          / fb:login-button scope="public_profile,email" onlogin="checkLoginState();"

      /! /.navbar-collapse
    /! /.container
  /! Header
  a name="about"
  .intro-header
    .container
      .row
        .col-lg-12
          .intro-message
            h1 PeerLearning
            h2#status
            h3 A product by Avanti Learning Centres
            hr.intro-divider/
            - if current_user
              h4
                | Welcome, 
                = current_user.name
            - else
                h3 
                  a href="/auth/facebook" class="btn btn-lg btn-primary"
                    strong
                      | f | 
                    | Connect with Facebook
                    / img.img-responsive alt="" src=image_url("FBloginbutton.jpg") /
                strong
                    | OR
                br
                br
                button type="button" class="btn btn-lg btn-default" data-toggle="modal" data-target="#signUpFormModal"
                  | Tell us about you             
                  / div class="fb-login-button" data-max-rows="1" data-size="xlarge" data-show-faces="false" data-auto-logout-link="false" href="/auth/facebook"
                  /   | Connect with Facebook
                  / fb:login-button scope="public_profile,email" onlogin="checkLoginState();"
                  / = link_to 'Connect with Facebook', '/auth/facebook', id: 'sign_in'
                
    /! /.container
  /! /.intro-header
  /! Page Content
  a name="services"
  .content-section-a
    .container
      .row
        .col-lg-5.col-sm-6
          hr.section-heading-spacer/
          .clearfix
          h2.section-heading
            | Death to the Stock Photo:
            br>/
            | Special Thanks
          p.lead
            | A special thanks to
            a href="http://join.deathtothestockphoto.com/" target="_blank"  Death to the Stock Photo
            | for providing the photographs that you see in this template. Visit their website to become a member.
        .col-lg-5.col-lg-offset-2.col-sm-6
          img.img-responsive alt="" src=image_url("ipad.png") /
    /! /.container
  /! /.content-section-a
  .content-section-b
    .container
      .row
        .col-lg-5.col-lg-offset-1.col-sm-push-6.col-sm-6
          hr.section-heading-spacer/
          .clearfix
          h2.section-heading
            | 3D Device Mockups
            br
            | by PSDCovers
          p.lead
            | Turn your 2D designs into high quality, 3D product shots in seconds using free Photoshop actions by
            a href="http://www.psdcovers.com/" target="_blank"  PSDCovers
            |! Visit their website to download some of their awesome, free photoshop actions!
        .col-lg-5.col-sm-pull-6.col-sm-6
          img.img-responsive alt="" src=image_url("dog.png") /
    /! /.container
  /! /.content-section-b
  .content-section-a
    .container
      .row
        .col-lg-5.col-sm-6
          hr.section-heading-spacer/
          .clearfix
          h2.section-heading
            | Google Web Fonts and
            br>/
            | Font Awesome Icons
          p.lead
            | This template features the 'Lato' font, part of the
            a href="http://www.google.com/fonts" target="_blank"  Google Web Font library
            |, as well as
            a href="http://fontawesome.io" target="_blank"  icons from Font Awesome
            |.
        .col-lg-5.col-lg-offset-2.col-sm-6
          img.img-responsive alt="" src=image_url("phones.png") /
    /! /.container
  /! /.content-section-a
  a name="contact"
  .banner
    .container
      .row
        .col-lg-6
          h2 Connect to Start Bootstrap:
        .col-lg-6
          ul.list-inline.banner-social-buttons
            li
              a.btn.btn-default.btn-lg target="_blank" href="https://twitter.com/amitmutrezas"
                i.fa.fa-twitter.fa-fw
                span.network-name Twitter
            li
              a.btn.btn-default.btn-lg target="_blank" href="https://github.com/amitmutrezas"
                i.fa.fa-github.fa-fw
                span.network-name Github
            li
              a.btn.btn-default.btn-lg target="_blank" href="https://www.linkedin.com/in/amitmutrezas"
                i.fa.fa-linkedin.fa-fw
                span.network-name Linkedin
    /! /.container
  /! /.banner
  /! Footer
  footer
    .container
      .row
        .col-lg-12
          ul.list-inline
            li
              a href="#"  Home
            li.footer-menu-divider &sdot;
            li
              a href="#about"  About
            li.footer-menu-divider &sdot;
            li
              a href="#services"  Services
            li.footer-menu-divider &sdot;
            li
              a href="#contact"  Contact
            div class="fb-like" data-share="true" data-width="450" data-show-faces="true"
          p.copyright.text-muted.small Copyright &copy; ALC Pvt. Ltd. All Rights Reserved

/! Modal
#signUpFormModal.modal.fade aria-labelledby="myModalLabel" role="dialog" tabindex="-1" 
  .modal-dialog role="document" 
    .modal-content
      .modal-header
        button.close aria-label="Close" data-dismiss="modal" type="button" 
          span aria-hidden="true"  &times;
        h4#myModalLabel.modal-title Enter details below
      .modal-body
        .form-container 
          == render partial: 'form', locals: { form_object: @user }
      .modal-footer
        / button.btn.btn-default data-dismiss="modal" type="button"  Close
        / button.btn.btn-primary#submit-details type="button"  Submit 

app/views/homes/new.html.slim
h1 New home

== render 'form'

= link_to 'Back', homes_path

app/views/homes/show.html.slim
p#notice = notice


= link_to 'Edit', edit_home_path(@home)
'|
= link_to 'Back', homes_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Peerlearning - A new way for learning by Avanti</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href="http://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">
  <%= csrf_meta_tags %>
</head>
<body>

<script>
  // This is called with the results from from FB.getLoginStatus().
  function statusChangeCallback(response) {
    console.log('statusChangeCallback');
    console.log(response);
    // The response object is returned with a status field that lets the
    // app know the current login status of the person.
    // Full docs on the response object can be found in the documentation
    // for FB.getLoginStatus().
    if (response.status === 'connected') {
      // Logged into your app and Facebook.
      testAPI();
    } else if (response.status === 'not_authorized') {
      // The person is logged into Facebook, but not your app.
      document.getElementById('status').innerHTML = 'Please log ' +
        'into this app.';
    } else {
      // The person is not logged into Facebook, so we're not sure if
      // they are logged into this app or not.
      document.getElementById('status').innerHTML = 'Please log ' +
        'into Facebook.';
    }
  }

  // This function is called when someone finishes with the Login
  // Button.  See the onlogin handler attached to it in the sample
  // code below.
  function checkLoginState() {
    FB.getLoginStatus(function(response) {
      statusChangeCallback(response);
    });



    // Now that we've initialized the JavaScript SDK, we call
    // FB.getLoginStatus().  This function gets the state of the
    // person visiting this page and can return one of three states to
    // the callback you provide.  They can be:
    //
    // 1. Logged into your app ('connected')
    // 2. Logged into Facebook, but not your app ('not_authorized')
    // 3. Not logged into Facebook and can't tell if they are logged into
    //    your app or not.
    //
    // These three cases are handled in the callback function.

    FB.getLoginStatus(function(response) {
      statusChangeCallback(response);
    });
  }

  window.fbAsyncInit = function() {
    FB.init({
      appId      : '796163203819756',
      cookie     : true,
      xfbml      : true,
      version    : 'v2.6'
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));

  function testAPI() {
    console.log('Welcome!  Fetching your information.... ');
    FB.api('/me', function(response) {
      console.log('Successful login for: ' + response.name);
      document.getElementById('status').innerHTML =
        'Thanks for logging in, ' + response.name + '!';
    });
  }
</script>

<%= yield %>

</body>
</html>

app/views/users/_form.html.slim
= form_for form_object , html: {class: 'form-horizontal',role: 'form', "data-toggle" => 'validator'} do |f|
      .form-container-unit
        = f.label :name
        = f.text_field :name, autofocus: true, class: "form-control", placeholder: t("user.p-name"), "data-error" => t("user.name"), required: true
        /= errors_for @user, :name
        .help-block.with-errors
      .form-container-unit
        = f.label :email
        = f.text_field :email, autofocus: true, class: "form-control", placeholder: t("user.p-email"), "data-error" => t("user.email"), required: true
        /= errors_for @user, :email
        .help-block.with-errors
      .form-container-unit
        = f.label :phone_number
        = f.text_field :phone_number, autofocus: true, class: "form-control", placeholder: t("user.p-phone_number"), "data-error" => t("user.phone_number"), required: true
        /= errors_for @user, :phone_number
        .help-block.with-errors
      .form-container-unit#save-details
        = f.submit 'Submit',class: "btn btn-lg btn-primary btn-block"

app/views/users/index.html.slim
body
  /! Navigation
  nav.navbar.navbar-default.navbar-fixed-top.topnav role="navigation"
    .container.topnav
      /! Brand and toggle get grouped for better mobile display
      .navbar-header
        button.navbar-toggle data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button"
          span.sr-only Toggle navigation
          span.icon-bar
          span.icon-bar
          span.icon-bar
        div.navbar-brand.topnav
          - if current_user
            | Signed in as &nbsp;
            strong
              = current_user.name
            |, &nbsp;
            strong.h2
              = link_to 'Sign out', signout_path, id: 'sign_out'
          - else
            = link_to 'Sign in with Facebook', '/auth/facebook', id: 'sign_in'
        / a.navbar-brand.topnav href="/auth/facebook"  onclick="checkLoginState()" Log in with Facebook
      /! Collect the nav links, forms, and other content for toggling
      #bs-example-navbar-collapse-1.collapse.navbar-collapse
        ul.nav.navbar-nav.navbar-right
          li
            a href="#about"  About
          li
            a href="#services"  Services
          li
            a href="#contact"  Contact
          / fb:login-button scope="public_profile,email" onlogin="checkLoginState();"

      /! /.navbar-collapse
    /! /.container
  /! Header
  a name="about"
  .intro-header
    .container
      .row
        .col-lg-12
          .intro-message
            h1 PeerLearning
            h2#status
            h3 
              | A product by 
              a href="http://www.avanti.in" target="_blank" Avanti Learning Centres
            hr.intro-divider/
            - if current_user
              h4
                | Welcome, 
                = current_user.name
            - else
                h3 
                  a href="/auth/facebook" class="btn btn-lg btn-primary"
                    strong
                      | f | 
                    | Connect with Facebook
                    / img.img-responsive alt="" src=image_url("FBloginbutton.jpg") /
                strong
                    | OR
                br
                br
                button type="button" class="btn btn-lg btn-default" data-toggle="modal" data-target="#signUpFormModal"
                  | Tell us about you             
                  / div class="fb-login-button" data-max-rows="1" data-size="xlarge" data-show-faces="false" data-auto-logout-link="false" href="/auth/facebook"
                  /   | Connect with Facebook
                  / fb:login-button scope="public_profile,email" onlogin="checkLoginState();"
                  / = link_to 'Connect with Facebook', '/auth/facebook', id: 'sign_in'
                
    /! /.container
  /! /.intro-header
  /! Page Content
  a name="services"
  .content-section-a
    .container
      .row
        .col-lg-5.col-sm-6
          hr.section-heading-spacer/
          .clearfix
          h2.section-heading
            | Online Classroom Program:
            / br>/
            / | Special Thanks
          p.lead
            | We provide you access to the content created by 
            a href="http://avanti.in/" target="_blank"  Avanti 
            | faculty. 
            | Take control of your learning by working on the skills you choose at your own pace with our online classes.
        .col-lg-5.col-lg-offset-2.col-sm-6
          img.img-responsive alt="" src=image_url("ipad.png") /
    /! /.container
  /! /.content-section-a
  .content-section-b
    .container
      .row
        .col-lg-5.col-lg-offset-1.col-sm-push-6.col-sm-6
          hr.section-heading-spacer/
          .clearfix
          h2.section-heading
            | Online Test Series
            / br
            / | by PSDCovers
          p.lead
            | Each test is followed by a detailed solution and a comprehensive graphical performance analysis.
            | The analysis is laid out section wise and broken down into questions wise analysis, difficulty level and the analysis 
            | of your attempt.
        .col-lg-5.col-sm-pull-6.col-sm-6
          img.img-responsive alt="" src=image_url("test_series.jpg") /
    /! /.container
  /! /.content-section-b
  .content-section-a
    .container
      .row
        .col-lg-5.col-sm-6
          hr.section-heading-spacer/
          .clearfix
          h2.section-heading
            | Delhi
          p.lead
            | 2nd Floor,
            br>/
            | 212 Shahpur Jat,
            br>/
            | New Delhi – 110049
            br>/
            | Email: info@avanti.in
            / a href="http://www.google.com/fonts" target="_blank"  Google Web Font library
            / |, as well as
            / a href="http://fontawesome.io" target="_blank"  icons from Font Awesome
            / |.
        .col-lg-5.col-lg-offset-2.col-sm-6
          hr.section-heading-spacer/
          .clearfix
          h2.section-heading
            | Mumbai
          p.lead
            | 501, Rajghor Empire,
            br>/
            | J.V. Road, Ghatkopar West,
            br>/
            | Mumbai – 400086
            br>/
            | Email: info@avanti.in
            / object type="text/html" data="http://localhost:3002" width="800px" height="600px" style="overflow:auto;border:5px ridge blue"
    /! /.container
  /! /.content-section-a
  a name="contact"
  .banner
    .container
      .row
        .col-lg-6
          h2 
            | Connect with us:
        .col-lg-6
          ul.list-inline.banner-social-buttons
            li
              a.btn.btn-default.btn-lg target="_blank" href="https://www.facebook.com/avantilearningcentres"
                i.fa.fa-github.fa-fw
                span.network-name Facebook
              
            li
              a.btn.btn-default.btn-lg target="_blank" href="https://twitter.com/AvantiLC"
                i.fa.fa-twitter.fa-fw
                span.network-name Twitter
            li
              a.btn.btn-default.btn-lg target="_blank" href="https://plus.google.com/101211218250872912164"
                i.fa.fa-linkedin.fa-fw
                span.network-name Google+
    /! /.container
  /! /.banner
  /! Footer
  footer
    .container
      .row
        .col-lg-12
          ul.list-inline
            li
              a href="#"  Home
            li.footer-menu-divider &sdot;
            li
              a href="#about"  About
            li.footer-menu-divider &sdot;
            li
              a href="#services"  Services
            li.footer-menu-divider &sdot;
            li
              a href="#contact"  Contact
            / div class="fb-like" data-share="true" data-width="450" data-show-faces="true"
          p.copyright.text-muted.small Copyright &copy; ALC Pvt. Ltd. All Rights Reserved

/! Modal
#signUpFormModal.modal.fade aria-labelledby="myModalLabel" role="dialog" tabindex="-1" 
  .modal-dialog role="document" 
    .modal-content
      .modal-header
        button.close aria-label="Close" data-dismiss="modal" type="button" 
          span aria-hidden="true"  &times;
        h4#myModalLabel.modal-title Enter details below
      .modal-body
        .form-container 
          == render partial: 'form', locals: { form_object: @user }
      .modal-footer
        / button.btn.btn-default data-dismiss="modal" type="button"  Close
        / button.btn.btn-primary#submit-details type="button"  Submit 